### ISSUE TITLE
Defaults / requests to allow array of avoidances (instead of a single value)

### ISSUE THREAD

**Issue by rpocklin** [Skalar/google_distance_matrix#18]
In `configuration.rb` it defines avoidances as
`validates :avoid, inclusion: {in: ["tolls", "highways"]}, allow_blank: true` and doesn't allow assigning this attribute to an array value, all requests fail in this case.

ie. defining with avoids = ['tolls', 'highways'] fails.

It would be great to also support `ferries` and `indoor` avoidances.

**Comment by thhermansen** [comment]
Hi,

I took a look at the [restrictions in the docs](https://developers.google.com/maps/documentation/distance-matrix/intro#RequestParameters). Does this mean that each added value to avoid should be added  to the URL as it's own get param? Ex: `https://maps.googleapis.com/maps/api/distancematrix/json?avoid=tolls&avoid=indoor`, or is it another way of serialising multiple avoid values in to one avoid get param?

I may have some time looking in to it the next weekend. If you got the time and want to take a go at it please feel free and I'll take a look at your code in a pull request.

**Comment by rpocklin** [comment]
I just looked at the docs again, and it doesn't allow for multiples for `avoid` in this particular API (it does for the javascript version of this API though!) so all that can be done is add the extra options and that's it :P

**Comment by thhermansen** [comment]
Thank you! Feel free to submit a pull request for the change if you got the time. I may do it if I find the time, but right now I have a bit on my plate :)

**Comment by rpocklin** [comment]
See #23

**Comment by thhermansen** [comment]
Thank you! I merged it now and will be releasing a new version of the gem soon.
