### ISSUE TITLE
Updating requests to use new attributes / properties

### ISSUE THREAD

**Issue by rpocklin** [Skalar/google_distance_matrix#19]
As per https://developers.google.com/maps/documentation/distance-matrix/intro#RequestParameters
it would be great to add the following as valid attributes in requests:

`transit_routing_preference`
`traffic_model`

Also the `sensor` argument is now deprecated and could be removed.

Happy to submit a PR.

**Comment by thhermansen** [comment]
Thank you for the request. Feel free to submit a PR and I'll take a look at it. Please remember to write some tests as well.

In regards to the sensor being deprecated you can submit that change as it's own pull request if you have the time. Maybe we should add a deprecation warning if people use it in one release, and in a later release simply remove it.

**Comment by rpocklin** [comment]
See #21

**Comment by thhermansen** [comment]
Thank you. The change has been merged.
