### ISSUE TITLE
ActiveSupport::Notifications.instrument

### ISSUE THREAD

**Issue by aceunreal** [Skalar/google_distance_matrix#25]
I have noticed the following https://github.com/Skalar/google_distance_matrix/blob/master/lib/google_distance_matrix/client.rb#L15
```
instrumentation = {url: url}.merge(options[:instrumentation] || {})

response = ActiveSupport::Notifications.instrument "client_request_matrix_data.google_distance_matrix", instrumentation do
  Net::HTTP.get_response uri
end
```

Won't this output the `url` in the logs? AFAIK the url contains a Google Map key

**Comment by thhermansen** [comment]
Hi,

That is a good catch. The Google API key was added in [v0.0.2](https://github.com/Skalar/google_distance_matrix/blob/master/CHANGELOG.md#v020) and I didn't think of that when I merged the pull request containing the option to use google api key.

If you like you may submit a pull request, or I'll take a look at it when I got some extra time.

**Comment by aceunreal** [comment]
What are your thoughts around the changes needed here?

**Comment by thhermansen** [comment]
My initial thought was to filter the URL and replace parts of the query param `key=top-secret-thing-here` with something like `key=[FILTERED]`. Now, that does not ensure that we in the future forget to filter new secret params, but maybe it is good enough? Or maybe we could put in our configuration objects query  params it should filter to make it easy to maintain and customisable.

I think [this](https://github.com/Skalar/google_distance_matrix/blob/master/lib/google_distance_matrix/log_subscriber.rb#L4) may be a good place to apply such a filter on `event.payload[:url]` before it is logged.

**Comment by aceunreal** [comment]
I like the idea of query params to filter so it can handle both `API key` and `signed URLs to use with a Google Business account`
