### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by thibault261** [Skalar/google_distance_matrix#37]
Hi,

I have installed your gem today and when i launch my server, i have this error : 

> /home/sycomore/.rvm/gems/ruby-2.0.0-p247/gems/google_distance_matrix-0.5.0/lib/google_distance_matrix/url_builder.rb:3:in `require_relative': /home/sycomore/.rvm/gems/ruby-2.0.0-p247/gems/google_distance_matrix-0.5.0/lib/google_distance_matrix/url_builder/polyline_encoder_buffer.rb:15: syntax error, unexpected ')' (SyntaxError)
> 

In the file "polyline_encoder_buffer.rb" at line 15 we have : 
`def flush(to:)`
I think it must be :
`def flush(to)`
No ?

Thanks a lot,
Thibault.

**Comment by thhermansen** [comment]
Hi,

As all [tests pass on different versions of Ruby](https://travis-ci.org/Skalar/google_distance_matrix) my guess would be that it has something to do the Ruby version you are using.

Are you using 2.0.0? Please try upgrading to any of the Ruby version as I don't think 2.0.0 is supported by this gem.

**Comment by thhermansen** [comment]
Hello again,

I didn't hear back from you and I think ruby version is the issue, thus I'm closing this issue now.
