### ISSUE TITLE
error output when calling matrix.data

### ISSUE THREAD

**Issue by therrick** [Skalar/google_distance_matrix#5]
When I attempt to call the GoogleDistanceMatrix::Matrix#data method, I get a proper result, but it also logs an ArgumentError triggered by logging code in log_subscriber.rb.

My environment: 
- ruby 2.1.5
- rails 4.1.6
- mac osx yosemite

I can recreate the error by creating a new, vanilla rails project, adding the google_distance_matrix gem to the Gemfile, running 'bundle' and then running the following commands at the 'rails c' console:

```
2.1.5 :007 > matrix = GoogleDistanceMatrix::Matrix.new
 => #<GoogleDistanceMatrix::Matrix origins: [], destinations: []>
2.1.5 :008 > origin = GoogleDistanceMatrix::Place.new lng: -78.49585, lat: 38.055403
 => #<GoogleDistanceMatrix::Place lat: 38.055403, lng: -78.49585>
2.1.5 :009 > dest = GoogleDistanceMatrix::Place.new lng: -78.46844, lat: 38.024637
 => #<GoogleDistanceMatrix::Place lat: 38.024637, lng: -78.46844>
2.1.5 :010 > matrix.origins << origin
 => [#<GoogleDistanceMatrix::Place lat: 38.055403, lng: -78.49585>]
2.1.5 :011 > matrix.destinations << dest
 => [#<GoogleDistanceMatrix::Place lat: 38.024637, lng: -78.46844>]
2.1.5 :012 > matrix.data
Could not log "client_request_matrix_data.google_distance_matrix" event. ArgumentError: wrong number of arguments (2 for 0..1) ["/Users/tom/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/logger.rb:433:in `info'", "/Users/tom/.rvm/gems/ruby-2.1.5@distance_test/gems/google_distance_matrix-0.1.1/lib/google_distance_matrix/log_subscriber.rb:8:in `client_request_matrix_data'",
...
 => [[#<GoogleDistanceMatrix::Route origin: #<GoogleDistanceMatrix::Place lat: 38.055403, lng: -78.49585>, destination: #<GoogleDistanceMatrix::Place lat: 38.024637, lng: -78.46844>, status: "ok", distance_text: "6.0 km", distance_in_meters: 6016, duration_text: "8 mins", duration_in_seconds: 497>]]
```

The method returns the proper result, but I don't want the extra error log entry in our logs.  Is there some way I can fix or suppress this error?

**Comment by thhermansen** [comment]
I think I have fixed it. Will release new version of this gem pretty soon.

**Comment by therrick** [comment]
I referenced the latest commit in my gemfile and can confirm that it fixes the error that was being logged.  Thanks for the quick fix!

However, in order to use it, I had to update rails to 4.2.0 because of this conflict:

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    google_distance_matrix (>= 0) ruby depends on
      activesupport (>= 3.2.13, ~> 4.2.0) ruby

    rails (= 4.1.6) ruby depends on
      activesupport (4.1.6)
```

It's not really a problem for me to move up to 4.2.0, but just wanted to make sure the new requirement was intentional.

**Comment by thhermansen** [comment]
Please try version 0.1.3. I have set it to be a bit more optimistic in regards to the gems it depends on.
