### ISSUE TITLE
Support for api_key required

### ISSUE THREAD

**Issue by nigelgomez** [Skalar/google_distance_matrix#7]
Is it possible to add 'API key' in GoogleDistanceMatrix::Configuration:: attributes?
We are should get a provision to use google_distance_matrix API using API-key instead of client_ID/secret key.

**Comment by thhermansen** [comment]
Hi,

Yes, I think that should be possible. Feel free to fork and make a pull request and I'll look at it when I have time. Keep in mind that requests executed with client and signature does not seem to require the API key.

**Comment by thhermansen** [comment]
API key has been added as a configuration option. Will be included in the next release of the gem.

**Comment by nigelgomez** [comment]
@thhermansen Thanks for getting this resolved.

**Comment by thhermansen** [comment]
No problem. Send your gratitude to @lsanwick :-)
